### ISSUE TITLE
Increase size of Mysql VDI

### ISSUE THREAD

**Issue by JamesDevware** [clwdev/precip#61]
Exodus database is BIG! That + some other databases and the 32gb limit can be reached causing strange issues. I have increased this to 64gb (currently sitting at 40gb)

Proposed solution is to either increase this in the vagrant file or allow this to be configured in config.rb Please let me know which you would prefer and I will raise a PR accordingly.

**Comment by jeffgeorge** [comment]
Same as #60, new variable please. I'm fine with you handling both of these in the same PR.

Only question with this one is what the migration path is. What happens if you set a new filesize and reprovision? does vagrant_persistent_storage intelligently resize the volume? What happens if you go large to small?

**Comment by JamesDevware** [comment]
Unfortunately not, the only way I know to change it is to nuke the VDI (which is a pain as the os is still looking for it) and then reprovision.
